[package]
name = "csv-size-diff"
version = "0.1.0"
edition = "2018"
authors = ["Hernando Castano <hernando@hcastano.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
csv = "1.1"
serde = { version = "1.0", features = ["derive"] }
